name:                haskell-tdlib-generator
version:             0.1.0.0
github:              "mejgun/haskell-tdlib-generator"
license:             BSD3
author:              "mejgun"
maintainer:          "example@example.com"
copyright:           "2023 mejgun"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mejgun/haskell-tdlib-generator#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  language:    GHC2021
  source-dirs: src
  dependencies:
  - mtl
  - text
  - unordered-containers
  default-extensions:
  - OverloadedStrings
  - NoFieldSelectors
  - OverloadedRecordDot
  - DuplicateRecordFields

executables:
  haskell-tdlib-generator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-tdlib-generator

tests:
  haskell-tdlib-generator-test:
    language:    GHC2021
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-tdlib-generator
    - text
    - hspec
    - directory
    default-extensions:
    - OverloadedStrings
    - NoFieldSelectors
    - OverloadedRecordDot
    - DuplicateRecordFields
